version: "3.7"

services:
  admin-backend:
    container_name: portfolio
    image: hub.hamdocker.ir/behnamkvl/portfolio
    restart: on-failure
    expose:
      - 8080
    ports:
      - "49160:8080"

  nginx:
    container_name: nginx
    image: hub.hamdocker.ir/behnamkvl/portfolionginx
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - admin-backend
