version: "3.7"

services:
  admin-backend:
    container_name: portfolio
    image: behnamkvl/portfolio
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    expose:
      - 8080
    ports:
      - "49160:8080"

  nginx:
    container_name: nginx
    image: behnamkvl/portfolionginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - admin-backend
