FROM nginx:1.19.0

RUN rm /etc/nginx/conf.d/default.conf
EXPOSE 80
COPY nginx.conf /etc/nginx/conf.d

# su root
USER root
RUN apt-get update && apt-get install certbot -y
RUN apt-get install python3-certbot-nginx -y
# RUN nginx -t && nginx -s reload



# ENTRYPOINT ["certbot", "--nginx"] certbot --nginx -d behnamkvl.me -d www.behnamkvl.me
